# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manifold < Formula
  desc "Simple Procfile-based process manager"
  homepage "https://github.com/blvrd/manifold"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_darwin_amd64.tar.gz"
      sha256 "4a231f4f6346c9dd90f354ec5682889feeeb77bf7471c61d175dd9ed89f35df4"

      def install
        bin.install "manifold"
      end
    end
    on_arm do
      url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_darwin_arm64.tar.gz"
      sha256 "d8eab3f9b9fd3e69c0b0609fab615cfe89847aea1a3e72181bbdd41c36e7009b"

      def install
        bin.install "manifold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_linux_amd64.tar.gz"
        sha256 "518a2e0aa2ef4261c79e211aa26a080e393d856778f0590496013bfe3d0cf8e9"

        def install
          bin.install "manifold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_linux_arm64.tar.gz"
        sha256 "1380360dbf06b53f7ac0f216231ba6762b635c882c8f1b08230cd26c59ce9d50"

        def install
          bin.install "manifold"
        end
      end
    end
  end
end
