# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manifold < Formula
  desc "Simple Procfile-based process manager"
  homepage "https://github.com/blvrd/manifold"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_darwin_amd64.tar.gz"
      sha256 "cf95e110ed8aabf073dd0cf4eacdaa99a81e37ecb3a05865fc6be7800af39b0d"

      def install
        bin.install "manifold"
      end
    end
    on_arm do
      url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_darwin_arm64.tar.gz"
      sha256 "14afb74d4b3b07bd2c0391584014b6715e187f21cc9581cc960f8d966d2fe5f7"

      def install
        bin.install "manifold"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_linux_amd64.tar.gz"
        sha256 "9e4d31cfefd61a4a2f9cc6b7a67049f7db62a1b8f3bd5f5ced0cd601dc784db9"

        def install
          bin.install "manifold"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blvrd/manifold/releases/download/v0.1.0/manifold_0.1.0_linux_arm64.tar.gz"
        sha256 "6b42cd2144859190263870ef9d2b604343ba3e7c86c6724e063dc899771a4c66"

        def install
          bin.install "manifold"
        end
      end
    end
  end
end
